version: "3"
services:
  model:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        INPUT_FILE: ${INPUT_FILE}
        OUTPUT_FILE: ${OUTPUT_FILE}
    volumes:
      - "./data:/data"
    env_file: ".env"

volumes:
  data:
    driver: local